- match:
    dependency_name: FluentValidation
    update_type: all

- match:
    dependency_name: Moq
    update_type: all
    
- match:
    dependency_name: Fody
    update_type: all

- match:
    dependency_name: Particular.Packaging
    update_type: all
